### ISSUE TITLE
Can't preview newly created documents with static generated websites

### ISSUE THREAD

**Issue by liqueflies** [nuxt-community/prismic-module#109]
Hello,
I am facing an issue that if I am trying to preview a new created document (for example a blog post) into a static generated sites (hosted into netlify) it redirects me to https://mysite.co/my-uid-newly-created it goes to 404.

Anyone faced this issue? Any workaround?

Many thanks <3

Here to help,
L.

**Comment by lihbr** [comment]
Hey @liqueflies thanks for the report! Can you share your Prismic repository name please? We're aware that preview is broken and in the process of being fixed on some repositories 🙁

**Comment by liqueflies** [comment]
Hi @lihbr ,

here my config (with repo name):

```
  prismic: {
    endpoint: 'https://diaridellacinquecento.cdn.prismic.io/api/v2',
    linkResolver: '@/plugins/link-resolver',
    htmlSerializer: '@/plugins/html-serializer',
  },
```

let me know , thank you :)

L.

**Comment by lihbr** [comment]
Hi @liqueflies sorry for the delay.

Configuration is looking good. I also checked your repository and previews should be working fine with it. This also means that I'm starting to be clueless regarding what might be wrong ^^' By any chance on what browser are you trying to preview? (we know Safari has trouble with them due to its cookie policy)

If you can share me your whole Nuxt config that might be helpful, also if you're comfortable with it I'm happy to get an invite to your repository so I can have a quick look at what's wrong or not. Thanks!

**Comment by liqueflies** [comment]
Hi @lihbr,
I have searched a lot in these days and I found the problem: netlify redirect to 404 if page not exist because of a nuxt default settings of generate: `{ fallback: 404  }`

I switched to `{ fallback: true }` and now goes to the `_uid.vue` page generating correct preview.

Thanks for your support <3
