### ISSUE TITLE
Preview state is not honored when navigating within SPA

### ISSUE THREAD

**Issue by aaronransley** [nuxt-community/prismic-module#128]
I'm having trouble with the previews feature not properly reflecting drafted changes in a release. 
I am creating a `target: 'static'` build using `yarn generate`.

If I preview the release to my local machine running a freshly `yarn generate`d `~/dist` folder, the initial page load shows production content, and then the preview functionality kicks in on the client side and properly updates content for whichever page I'm on.

However, if I then navigate to a second route via NuxtLink, the `payload.js` is loaded from the `~/dist` site, and the preview functionality does not re-apply itself to the new route.

I'm curious how I can:

1. `yarn generate` a site that properly reflects draft content that has been associated with a release in Prismic? Is there an endpoint or simple solution to point the SSG process to draft / release content from Prismic?
2. At the very least, have Nuxt properly refresh with active Prismic preview content when arriving at a new route within the SPA.

**I created a reproduction repository here:**
https://github.com/aaronransley/nuxt-prismic-ssg-preview-broken

**And here is my Prismic repository**, which is cannot export due to the free tier (perhaps you can see it if you are a Prismic employee, I am unsure):
https://nuxt-prismic-previews-test.prismic.io

**Data model of the Prismic repository, in case it's helpful:**
* homepage <singleton>
  * slug `<uid>`
  * text area `<richtext>`
* journal_entry `<repeatable>`
  * slug `<uid>`
  * title `<title>`
  * text area `<richtext>`
* content
  * 1x homepage singleton
  * 2x journal_entry instances

**Comment by lihbr** [comment]
Hey @aaronransley, thanks for submitting an issue!

Regarding your preview issue, you should be able to see previewed content, even when navigating through pages. I'll have a look at your reproduction this afternoon, thanks for submitting one 🙏

Regarding your first question, _generating a website with content from a release_:

You can do that by specifying a specific `ref` to use to the client. By default it uses the master ref (production content), [more info about it here](https://prismic.io/docs/technologies/query-options-reference-javascript#ref). To do that you need to provide the `ref` as an option when calling the API:

```javascript
export default {
  async asyncData({ $prismic, params, error }) {
    const document = await $prismic.api.getByUID('page', params.uid, { ref: "your-release-ref" });

    /* ... */
  }
}
```

To get available refs in your repository you can simply call `/api/v2` with a `GET` request, the response object should feature an array of available refs, currently for your repository it looks like so (apparently your API is fully public, if you ever tweak its visibility you might need to also provide your access token as a query parameter: ``:
```javascript
{
  "refs": [
    {
      "id": "master",
      "ref": "YEakQRAAACMAAACk",
      "label": "Master",
      "isMasterRef": true
    },
    {
      "id": "YEalBhAAACEAAAQz",
      "ref": "YEalHBAAABAAAASX~YEakQRAAACMAAACk",
      "label": "test"
    }
  ],
  /* ... */
}
```

Thankfully you don't have to call this endpoint everything because Prismic API client takes care of saving refs it has found when inited, a full example to have your website generated from content in your "test" release would look like so:

```javascript
export default {
  async asyncData({ $prismic, params, error }) {
    const ref = $prismic.api.refs.find((i) => i.label === "test").ref;
    const document = await $prismic.api.getByUID('page', params.uid, { ref });

    /* ... */
  }
}
```

From here you're pretty free to implement any logic to have that working only on a staging website for example 🙂

**Comment by lihbr** [comment]
Okay regarding the initial preview issue across navigation I was able to confirm it as a valid bug. I worked on a fix, should land soon on NPM with version 1.2.5 of this module :)

**Comment by aaronransley** [comment]
Wonderful, thank you so much @lihbr!

Hopefully it's not too off-topic, but I'm curious if there's a way to lookup the latest preview refs in a similar way? Right now, it seems that a user needs to initiate a preview session from the Prismic admin interface. 

Ideally I'd love the flexibility to have my CI/CD pipeline reach _into Prismic_ to ask for the latest draft/preview content, even if it is not associated with an umbrella release. 

This would help me generate a continuously-deployed version of the static site for users who prefer to see all pending changes whole-cloth, rather than adding individual pending drafts to releases, etc.

I'll keep my eyes out for the new NPM release. Thank you again!

**Comment by lihbr** [comment]
Hey Aaron, 1.2.5 has been released on NPM 🎉

Regarding getting the ref of preview sessions I'm afraid that's not possible and you'll have to stick with the release workflow here. Being able to preview everything in draft is a nice feedback although, I'll bring it to our product team!
