### ISSUE TITLE
[RFC] Mechanism to checks if the ref is the most up to date one and triggers a refresh if not.

### ISSUE THREAD

**Issue by phillysnow** [nuxt-community/prismic-module#130]
In dev mode, if a users' browser does not have the most up-to-date ref because of a content change, then this causes a 403 when navigating the pages. 

We should implement a check on the ref to see if it's up to date and if not we should trigger a hard refresh.

**Linked forum topic:**
https://community.prismic.io/t/expired-token-access-token-403-error-on-some-page-visits-safari/4369/21

**Comment by lihbr** [comment]
*Update `05/04/2021`:*
1. I'm looking to understand more the root of the issue, in any case this won't land on v1 and if any will be part of v2

**Comment by phillysnow** [comment]
I think this is related:
https://community.prismic.io/t/vercel-nuxtjs-randomly-page-not-found/5209

**Comment by jutane** [comment]
Hi @lihbr 

This happens when content is updated in Prismic, this will update the master reference.

If someone is browsing the website when this happens, they continue to browse the site with the old master ref leading to an expiry, when this happens the application throws a 403 error and dies.

I built in a check in middleware on our site for each render to check if master ref has been updated, if it has it reloads the next page visit but isn't ideal as the page reloads.

This happens on production + development. 

Thanks
Jake

**Comment by lihbr** [comment]
Thanks for the additional info @jutane! That sounds better, I'll dig into it

**Comment by lihbr** [comment]
Hey there, sorry for the delay! Here are some updates on this issue:

- The `modern` option of the module introduced last year uses a version of the Prismic client that only caches the master ref for 5 seconds: https://prismic.nuxtjs.org/configuration#modern
   This should prevent such errors from happening in the future and voids the need for such a mechanism.

- The new Prismic client available on the new version of this module targeting Nuxt 3 (https://v3.prismic.nuxtjs.org) also uses the same caching strategy.

With that in mind I think we can consider this issue fixed/implemented. Thanks!
