### ISSUE TITLE
Folders with hyphens '-', causing the route generation to fail.

### ISSUE THREAD

**Issue by phillysnow** [nuxt-community/prismic-module#136]
When deploying a site on Netlify with a route like: `.../actueel/at-work/max-at-work/` it fails with the following error.
```
Error generating route "/actueel/at": This page could not be found
```

It doesn't seem related to the link resolver or the route resolver. The route is then generated at `.../max-at-work/` and the page queries fine. 

My thought is that it's probably related to this plugin or `Nuxt` since it generates the dynamic routes.

Any thoughts.

**Comment by lihbr** [comment]
Turns out it's an issue with the API itself, tracked internally here: https://github.com/prismicio/issue-tracker-wroom/issues/513

For anyone experiencing this issue you can migrate from the [`apiOptions.routes`](https://prismic.nuxtjs.org/configuration#new-routes-resolver) options to a classic [link resolver](https://prismic.io/docs/technologies/link-resolver-nuxtjs) to fix it.

We'll keep you updated here of the status of this issue 🙂

**Comment by lihbr** [comment]
*Update `05/04/2021`:*
1. A PR has been made to fix this, it should land shortly!

**Comment by lihbr** [comment]
Fix landed on the API a while ago ☺️
