### ISSUE TITLE
Library calls `/api/v2` for every request

### ISSUE THREAD

**Issue by ioanb7** [nuxt-community/prismic-module#65]
Hi,

For every API read this library does two requests. One to `/api/v2`, the other one to the callback of $prismic (for example to get a single by uid)

The first authentication request takes 450ms, the other one takes 150ms. This means the page takes at least 600ms to load.

Any workaround for this, or does it need a fork?

No where I can find this being mentioned in the docs other than here: https://prismic.io/docs/javascript/query-the-api/how-to-query-the-api `It is recommended to assign the API object to a variable, and use it for all queries of the same screen.`

**Comment by arnaudlewis** [comment]
Hi @ioanb7, this plugin relies on the prismic client of the `prismic-javascript` library.
When it calls `/api/v2`, it will retrieve information like the `ref` of your API to retrieve your content, the search url to query your content and many other needed info.
A `ref` is just an identifier of a particular version of your API. Each time you publish, it will update this ref.
This mechanism allow us to cache all the response for an unlimited time and we make sure that you won't face cache issue each time you publish since we change the ref and so, the url you use to fetch your content.
If we cache the call to `/api` it will also cache this `ref` and 2 scenarii:
- You have an old ref so you get an old content. If the TTL is short it's manageable.
- You have a lot of publish because a lot of people are working on the writing room, if you have more than 5 publish during the TTL, your calls will return a 403 because the api version is no longer available and that will cause a major issue.

Now regarding the response time, the call to `/api` need to hit our servers directly and even if it's small, it seems that we have some latency for this call and we are aware of this and the devops team is actively working on improving this.
The second call is way bigger but like I explained, we manage to cache your content forever so the second call just stop at the CDN and is always very fast except the first time after a publish.

So we are working to improve the response time and we'll continuously improve how we can manage some layer of cache on the client to prevent calling /api all the time, meaning also improvements on the backend too.

**Comment by ioanb7** [comment]
Hi @arnaudlewis , thank you for the explanation. Where can I subscribe to get updated when the latency issue is solved?

**Comment by arnaudlewis** [comment]
You can follow here on the progress page: https://prismic.io/progress
For now, /api hit our server from West Virginia but we'll redund our servers on multiple regions for this purpose. This improvement will appear on that page.
