### ISSUE TITLE
Error at nuxt generate when preview = false

### ISSUE THREAD

**Issue by lluishi93** [nuxt-community/prismic-module#69]
When I set preview to false at nuxt.config.js, I got the following result after running nuxt generate:

![image](https://user-images.githubusercontent.com/14786440/80165243-5e9e8300-85db-11ea-87f9-c8fdcd8943e8.png)

If I set the preview attribute to true, it works, but the thing is I don't want to generate the preview route.

**Comment by Atinux** [comment]
Hi @lluishi93 

Could you share your `nuxt.config.js` please?

**Comment by Atinux** [comment]
cc @hypervillain

**Comment by hypervillain** [comment]
It would mean that [this test](https://github.com/nuxt-community/prismic-module/blob/master/spec/index.spec.js#L154) isn't right. I'll dig into it today

**Comment by hypervillain** [comment]
@lluishi93, `preview` option does not disable the routes generator. Can you try adding a `disableGenerator` param to your config?

**Comment by lluishi93** [comment]
Hi, sorry for the late answer, I've been a bit busy. Few remarks on my problem with this bug:

- I'm using nuxt-router community module, so all my routes config is extracted in a route.js file.
- What I want to achieve is either:
   1. Generate preview route. By default, when preview is set to true, the generation itself fails.
I tried two ways to config the module. Assigning a preview route, and leaving the default config:
![image](https://user-images.githubusercontent.com/14786440/80954692-2b8b9900-8dfe-11ea-8e53-66c3f35f2bce.png)
![image](https://user-images.githubusercontent.com/14786440/80954772-4eb64880-8dfe-11ea-8fec-e61ce6c3685a.png)

Both resulted in the following output:
![image](https://user-images.githubusercontent.com/14786440/80954752-478f3a80-8dfe-11ea-978d-83a3bedb3211.png)

   2. Disable preview.
This is the bug we're talking about here. The config for this was:
![image](https://user-images.githubusercontent.com/14786440/80954821-668dcc80-8dfe-11ea-85c0-33409bf25429.png)

Resulting in the error you can see in the issue screenshot.

I tried two workarounds for both use cases:
- For disabling preview, I redirected the user to the home page.
- For enabling preview, I'd to follow this documentation:
https://prismic-nuxt.js.org/docs/preview#customizing-the-preview-page

Below you can see a screenshot showing both use cases:
![image](https://user-images.githubusercontent.com/14786440/80954954-a6ed4a80-8dfe-11ea-9bd2-6474a80ab8b1.png)

I assume this is issue is specific to my setup. With this, I do not get errors anymore, but it is a bit tricky and maybe it should be documented somewhere. Hope some of this info helped.

BTW, @hypervillain , where does that boolean can be setup?

**Comment by hypervillain** [comment]
Thank you for you detailed answer @lluishi93.
I think there are different issues that overlap here.

If setting `preview` to false creates a `Generated undefined routes` error, it's probably because your generate.routes config (https://nuxtjs.org/api/configuration-generate/#routes) is incorrect. Can you check that you end up with something like this in your Nuxt config file:

```javascript
  generate: {
    routes: ['/', ...routes]
  }

````

I'm not sure why setting `preview` to true fails at generating the preview file though. But in any case, if you don't want to generate the preview route, you should set the option to false and double check your generate configuration.

Also, we've just introduced a new Prismic generator, that maps your Prismic documents via the "routes" option and passes the resolved urls to the Nuxt generator:

```javascript
 modules: [
    ['@nuxtjs/prismic', {
      endpoint: 'https://repo.prismic.io/api/v2',
      disableGenerator: true || false,
      apiOptions: {
        routes: [{
          type: 'page',
          path: '/:uid'
        }]
      },
    }],
  ],
````

In your case, the Prismic generator is ignored, as you don't pass `apiOptions.routes`. So, the boolean I mentioned (`disableGenerator`) would not be of any use here.

**Comment by lihbr** [comment]
Hi @lluishi93,

Since this issue has not had recent activity I'll friendly close it and mark it as stale, feel free to reach out to us if you still encounter the issue, will happily reopen it if needed 🙂

Thanks for your contribution!
